name: Test/Lint
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --enable-all
